name: 'Setup Julia environment'
description: 'Setup a Julia environment and add it to the PATH'
author: 'Sascha Mann'
inputs: 
  version:
    description: 'The Julia version to download (if necessary) and use. Example: 1.0.4'
    default: '1'
  arch:
    description: 'Architecture of the Julia binaries. Defaults to x64.'
    required: false
    default: 'x64'
  show-versioninfo:
    description: 'Display InteractiveUtils.versioninfo() after installing'
    required: false
    default: 'false'
  cache-artifacts:
    description: 'Cache ~/.julia/artifacts. Will fail if no file matches **/Project.toml.'
    required: false
    default: 'true'
outputs:
  artifacts-cache-id:
    description: 'The cache id of the artifacts cache.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'green'
